### ISSUE TITLE
Failed to compile WASM

### ISSUE THREAD

**Issue by jmonster** [wilsonzlin/edgesearch#11]
~I suspect this is because I'm on an arm64 (Apple Silicon) machine and running an arm64 compiled version of edgesearch. When I attempt to run the provided x86 binary my script aborts with SIGILL (Illegal instruction).~

This is happening for me (with the same document/terms file) on macOS ARM and x86 freebsd .. so it's almost definitely user error?

```sh
RUST_BACKTRACE=1 edgesearch \
  --documents docs \
  --document-terms terms \
  --maximum-query-results 10 \
  --output-dir out \
  --data-store KV

Processing documents (0%)...
Processing documents (18.34%)...
Processing documents (36.68%)...
Processing documents (55.01%)...
Processing documents (73.35%)...
Processing documents (91.69%)...
There are 349 documents with 945 terms
1 chunks contain terms
1 chunks contain documents

error: unable to create target: 'No available targets are compatible with triple "wasm32-unknown-unknown-wasm"'
1 error generated.
thread 'main' panicked at 'Failed to compile WASM', src/build/wasm.rs:103:9
stack backtrace:
   0: std::panicking::begin_panic
   1: edgesearch::build::wasm::generate_and_compile_runner_wasm
   2: edgesearch::build::build
   3: edgesearch::main
```

snippet from `docs`:
```txt
{"timecode":4,"text":"<i>Sensors detect a ship\non an intercept course at warp speed.</i>","at":"11/4.jpg"}{"timecode":8,"text":"<i>Should we go to red alert?</i>","at":"11/8.jpg"}
```

snippet from `terms`:
```txt
t_sensors ,t_detect ,t_a ,t_shipon ,t_an ,t_intercept ,t_course ,t_at ,t_warp ,t_speed t_should ,t_we ,t_go ,t_to ,t_red ,t_alert 
```

**Comment by wilsonzlin** [comment]
It looks like the `clang` being invoked doesn't support the WASM target. LLVM comes with WASM [out of the box ](https://github.com/WebAssembly/wasi-sdk#about-this-repository) from version 9.0 upwards, are you using the latest version? I usually just download the latest [prebuilt LLVM](https://releases.llvm.org/download.html) and extract to somewhere in `$HOME`, avoiding any system/bundled packages.

**Comment by jmonster** [comment]
Oh, I was so close! I had installed llvm (with homebrew) but it did _not_ symlink it. I manually set my PATH to include it and 🚀 success! Thank you so much!
