### ISSUE TITLE
[Question] is search result paging available? 

### ISSUE THREAD

**Issue by jveres** [wilsonzlin/edgesearch#2]
Haven't found anything regarding paging in the code or in the examples so I'm curious if paging search results is available or could be easily added?

**Comment by wilsonzlin** [comment]
I had a quick look and it seemed relatively straightforward, so I implemented it. There is no difference in building or deploying but workers will need to built and deployed again. The API now returns a `continuation` value that should be set on future queries to get more results. I've updated the README with some sample code.

Haven't tested extensively but preliminary testing went OK. Let me know how it goes if you try it out.

**Comment by jveres** [comment]
That was quick, thanks. I'll create some tests and will let you know. One thing I noticed is that search in now broken in the [work-at-microsoft](https://github.com/wilsonzlin/edgesearch/tree/master/demo/work-at-microsoft) demo.

**Comment by wilsonzlin** [comment]
Thanks, I've updated the client for the demo.
