### ISSUE TITLE
How large can an index be?

### ISSUE THREAD

**Issue by cloudiercom** [wilsonzlin/edgesearch#3]
This is some super impressive work here, I've experimented with a similar approach but couldn't get within the CPU-limits. I don't have any experience with C though and didn't think of using Roaring Bitmaps, which makes a lot more sense!

Have you tested how large the max Index size can be?

I have 20MB of documents (30k), how large would they become when indexed here? 
When I tested with a JS-based search engine, the worker ran out of CPU-time at ~8MB, but searches where still fast enough (my target is < 1 second).

**Comment by wilsonzlin** [comment]
There is no hardcoded upper limit, and in theory Edgesearch should be able to scale to very large indices. The Wikipedia demo uses the page view counts dataset from https://dumps.wikimedia.org/other/pagecounts-ez, which contains over 10 million article titles and totals to 2.4 GB. The worker only uses around 60 KV entries and still retains fast performance.

The only limiting factor I can think of (other than cost) would be the Cloudflare Workers limit of the worker script size, which must contain a BST of index rows in KV (although even this could be moved to KV).

**Comment by amrutadotorg** [comment]
For more intensive CPU scripts you might also check Workers Unbound 
see: https://blog.cloudflare.com/introducing-workers-unbound/
