### ISSUE TITLE
New KV limits (25MB)

### ISSUE THREAD

**Issue by eidam** [wilsonzlin/edgesearch#6]
Hey, FYI the key value limit was recently raised to 25MB, which could improve some performance, right? 

https://developers.cloudflare.com/workers/platform/limits#kv

**Comment by wilsonzlin** [comment]
Thanks for the notice, just bumped the default chunk size to 25 MiB. This should mean fewer keys and cache misses.

**Comment by eidam** [comment]
Nice, can’t wait to try this out! 👍
