### ISSUE TITLE
Why not https://crates.io/crates/roaring?

### ISSUE THREAD

**Issue by newtack** [wilsonzlin/edgesearch#8]
Awesome project! 

We are using the above pure Rust library for roaring bitmaps for a wasm based application and was wondering why you opted for a C based implementation.

**Comment by wilsonzlin** [comment]
Thanks, and apologies for the late response. I initially left it to use `croaring-rs` as I wanted to be able to test the non-portable serialisation mechanism. Also, it appears that the Rust port does not support run optimisations. I've just tested it out and I was able to get around 27% better terms compression for the English Wikipedia dataset using `croaring-sys`.

I've updated the code to use the Rust port (`roaring`) library by default, however I've also added a `nonportable` feature to the Rust crate, if anyone wants to try it out.

**Comment by newtack** [comment]
Thanks!
